# Generated by Django 2.2.12 on 2021-04-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210413_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(default='0'),
        ),
    ]
